services:
  - type: web
    name: SAINI TXT DIRECT 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsainiop/Saini-txt-direct
    branch: main
    autoDeploy: false
    envVars:
      - key: 8057693409:AAEFd7AM8GKEqJcv16aaqKXxepkIVwgQWkE
        sync: false
      - key: 24513216
        sync: false
      - key: 2079c79959648d8bbd992c4101bfcda2
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
